name: kikao_homes
description: "A visitor management system for Kikao Homes. This app is designed to help manage visitors and their information efficiently."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.5
  shared_preferences: ^2.1.0
  supabase_flutter: ^2.9.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^16.3.2
  intl: ^0.19.0
  qr_code_scanner: ^1.0.0
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.12.0
  file_picker: ^6.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/house.jpg