// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaFGGzoCyNfNNlf2Ors6OGpTdDUfuhkA8',
    appId: '1:1089380066752:web:107812e4abedda15c91425',
    messagingSenderId: '1089380066752',
    projectId: 'kikaohomes',
    authDomain: 'kikaohomes.firebaseapp.com',
    storageBucket: 'kikaohomes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYcQ5t2tV2o9eOFmW_OiLAQgcoKrMriR8',
    appId: '1:1089380066752:android:47afe23039cdd84cc91425',
    messagingSenderId: '1089380066752',
    projectId: 'kikaohomes',
    storageBucket: 'kikaohomes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYl0_uUvNSuKRXGG9iFOfANPWb_YQBDuE',
    appId: '1:1089380066752:ios:e587a150571796b7c91425',
    messagingSenderId: '1089380066752',
    projectId: 'kikaohomes',
    storageBucket: 'kikaohomes.firebasestorage.app',
    iosBundleId: 'com.yourcompany.kikaoHomes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYl0_uUvNSuKRXGG9iFOfANPWb_YQBDuE',
    appId: '1:1089380066752:ios:e587a150571796b7c91425',
    messagingSenderId: '1089380066752',
    projectId: 'kikaohomes',
    storageBucket: 'kikaohomes.firebasestorage.app',
    iosBundleId: 'com.yourcompany.kikaoHomes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaFGGzoCyNfNNlf2Ors6OGpTdDUfuhkA8',
    appId: '1:1089380066752:web:3691709d9447ea44c91425',
    messagingSenderId: '1089380066752',
    projectId: 'kikaohomes',
    authDomain: 'kikaohomes.firebaseapp.com',
    storageBucket: 'kikaohomes.firebasestorage.app',
  );
}
